
apiVersion: devops.alauda.io/v1alpha1
kind: PipelineTaskTemplate
metadata:
  name: alaudaDeployService
  annotations:
    alauda.io/displayName.zh-CN: 更新服务
    alauda.io/displayName.en: DeployService
    alauda.io/description.zh-CN: 更新服务
    alauda.io/description.en: DeployService
    alauda.io/readme.zh-CN: 更新服务
    alauda.io/readme.en: DeployService
    alauda.io/version: v0.1
    alauda.io/style.icon: 
  labels:
    catgory: CD
spec:
  engine: gotpl
  body: |+
    script{
      timeout(time:{{.timeout}}, unit: "SECONDS"){
        alauda.withCluster("{{.containerInfo.clusterName}}", "{{.containerInfo.namespace}}"){
          def serviceID = alauda.service("{{.containerInfo.serviceName}}").
          withContainer("{{.containerInfo.containerName}}").
          withImage("{{.image.registry}}/{{.image.repository}}:{{.imageTag}}").
          withImageTag("{{.imageTag}}").
          {{- range $i,$item := .env}}
          withEnv("{{$item.Name}}", "{{$item.Value}}").
          {{- end}}
          withCommand("{{.command}}").
          withArgs("{{.args}}").
          deploy();
        }
      }
    }
  arguments:
    - name: containerInfo
      schema:
        type: alauda.io/newk8scontainermix
      display:
        type: alauda.io/newk8scontainermix
        name:
          zh-CN: "容器"
          en: "Container"
      required: true
    - name: command
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: "接入点"
          en: "Entrypoint"
      required: false
    - name: args
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: "执行命令"
          en: "Run Command"
      required: false
    - name: "image"
      schema:
        type: alauda.io/imagerepositorymix
      display:
        type: alauda.io/imagerepositorymix
        name:
          zh-CN: "更新使用的镜像"
          en: "Use Image "
      required: true
    - name: "imageTag"
      schema:
        type: string
      display:
        type: alauda.io/imagetag
        name:
          zh-CN: "镜像版本"
          en: "Image Tag"
      required: true
      default: latest
    - name: env
      schema:
        type: alauda.io/k8senv
      display:
        type: alauda.io/k8senv
        name:
          zh-CN: "环境变量"
          en: "environments"
    - name: timeout
      schema:
        type: int
      display:
        type: int
        name:
          zh-CN: "超时时间（秒）"
          en: "Timeout (s)"
      required: true
